### ISSUE TITLE
Error when using plugin in custom DSL

### ISSUE THREAD

**Issue by antoinedube** [openshift/jenkins-client-plugin#103]
I am trying to extract a part of code that I will be reusing in different script. Currently, it is directly in the Jenkinsfile. For example:
```groovy
stage('Check service directly from Jenkinsfile') {
     steps {
         script {
             openshift.withCluster("${OPENSHIFT_CLUSTER}") {
                 openshift.withProject("${OPENSHIFT_PROJECT}") {
                 def serviceSelector = openshift.selector('service', "${OPENSHIFT_SERVICE}")
                 def serviceDescription = serviceSelector.describe()
                 echo "service: ${serviceDescription}"
             }
         }
     }
 }
```
This is working as expected.

When extracting code in a groovy method (file vars/getServiceDescription.groovy): 
```groovy
def call(body) {
    def config = [:]
    body.resolveStrategy = Closure.DELEGATE_FIRST
    body.delegate = config
    body

    script {
        openshift.withCluster("${config.cluster}") {
            openshift.withProject("${config.project}") {
                def serviceSelector = openshift.selector('service', "${config.service}")
                def serviceDescription = serviceSelector.describe()
                echo "service: ${serviceDescription}"
            }
        }
    }
}
```
and calling it from my Jenkinsfile:
```groovy
stage('Check service from external method') {
    steps {
        getServiceDescription cluster: "${OPENSHIFT_CLUSTER}", project: "${OPENSHIFT_PROJECT}", service: "${OPENSHIFT_SERVICE}"
    }
}
```
the resulting error/stacktrace is:
```
java.nio.file.NoSuchFileException: /var/run/secrets/kubernetes.io/serviceaccount/token
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.newByteChannel(Files.java:407)
	at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
	at java.nio.file.Files.newInputStream(Files.java:152)
	at hudson.FilePath.read(FilePath.java:1771)
	at org.jenkinsci.plugins.workflow.steps.ReadFileStep$Execution.run(ReadFileStep.java:96)
	at org.jenkinsci.plugins.workflow.steps.ReadFileStep$Execution.run(ReadFileStep.java:86)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1$1.call(SynchronousNonBlockingStepExecution.java:49)
	at hudson.security.ACL.impersonate(ACL.java:260)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1.run(SynchronousNonBlockingStepExecution.java:46)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Any help would be appreciated.

**Comment by gabemontero** [comment]
Hey @antoinedube - the expected and actual values of your cluster and project params/env vars when you run the different permutations are needed for me to fully help.

I can tell you that if the plugin sees empty values for the cluster parameter, it will go with among other things the default location of the jenkins service account token mounted in a pod, where the plugin will assume you are running in a jenkins pod.

My guess is that:
a) you are not running jenkins in an openshift pod based on the exception
b) and value for the cluster you expect to be passed into `openshift.withCluster` is not getting passed in, but rather the empty string is

**Comment by antoinedube** [comment]
Hi, 

Thanks for your input, it helped. It seems that point a) of your guess is right. 

I will update my things knowing this. 

Thanks.
