### ISSUE TITLE
NPE when missing object is not helpful to users

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/jenkins-client-plugin#104]
Whenever I forget to wrap a call in `withCluster()` or try to `.object()` on something that doesn't exist, I get:

```
java.lang.NullPointerException: Cannot invoke method isSkipTlsVerify() on null object
	at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:91)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:48)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:35)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.methodCall(DefaultInvoker.java:19)
	at com.openshift.jenkins.plugins.OpenShiftDSL.buildCommonArgs(jar:file:/var/lib/jenkins/plugins/openshift-client/WEB-INF/lib/openshift-client.jar!/com/openshift/jenkins/plugins/OpenShiftDSL.groovy:368)
	at com.openshift.jenkins.plugins.OpenShiftDSL.buildCommonArgs(jar:file:/var/lib/jenkins/plugins/openshift-client/WEB-INF/lib/openshift-client.jar!/com/openshift/jenkins/plugins/OpenShiftDSL.groovy:351)
	at com.openshift.jenkins.plugins.OpenShiftDSL$OpenShiftResourceSelector._asSingleMap(jar:file:/var/lib/jenkins/plugins/openshift-client/WEB-INF/lib/openshift-client.jar!/com/openshift/jenkins/plugins/OpenShiftDSL.groovy:1069)
	at com.openshift.jenkins.plugins.OpenShiftDSL$OpenShiftResourceSelector.object(jar:file:/var/lib/jenkins/plugins/openshift-client/WEB-INF/lib/openshift-client.jar!/com/openshift/jenkins/plugins/OpenShiftDSL.groovy:1085)
```

This is not really a helpful stacktrace and if we could wrap it in some context that would help me remember to `withCluster()` or suggest that no object was selected it would be much more helpful.

/cc @gabemontero @bparees @jupierce

**Comment by gabemontero** [comment]
OK, some initial triage:

1) the NPE literally stems from the `currentContext` being null

2) the version of OpenShiftDSL.groovy that @stevekuznetsov is at here, based on the line numbers, and the fact that `_asSingeMap` calls `buildCommonArgs` is relatively old.  We are talking about commit 7a0dc00d18b1ccaebf685ff2b93dbc7bcd6c8a96 which is 10 weeks ago as of this comment.

`buildCommonArgs` is no longer called from `_asSingleMap`  since @jupierce changed how `_asSingleMap` works with commit 170b9d2d025a335e244d9828925073d16e64e71d two weeks ago.

Now, what to do:

- prior to @jupierce 's 170b9d2d025a335e244d9828925073d16e64e71d, this smelled like the need for another use of `dieIfWithout`, checking on `currentContext`

- but with this refactor, including the returning of an empty list on `object()` if we are not pointing to anything, I am going to close this ("fixed upstream" or however you are inclined to phrase it).

@stevekuznetsov - I plan on cutting a new version of the client plugin (v1.0.4) in the next day or two once I've finished triaging all the "week before Christmas" Jenkins fun that ensued while I was on PTO.  It should pick up @jupierce 's commits during that time, including the one I've referenced above.  And then I'll update the openshift jenkins centos image right after.

Let's see if you still see this after picking either that image or the latest plugin.

**Comment by jupierce** [comment]
@gabemontero buildCommonArgs might be a good place to a die-without-context in general. It would eliminate this error from other codepaths.

**Comment by gabemontero** [comment]
On Tue, Jan 2, 2018 at 3:29 PM, Justin Pierce <notifications@github.com>
wrote:

> @gabemontero <https://github.com/gabemontero> buildCommonArgs might be a
> good place to a die-without-context in general. It would eliminate this
> error from other codepaths.
>
Yeah I was wondering about that @jupierce, though the other uses seemed
more "top level" (withCluster, withProject, etc.) and so was going to
ask about that later on / off line (after making some progress on some of
the other issues).

We'll circle back, thanks.
