### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by GolanTrevize10** [openshift/jenkins-client-plugin#159]
Hi, we upgraded the plugin to the latest 1.0.12 version and we are getting the error below. I downgraded to 1.0.7 and it works again. We are using OC client version v3.6.0+c4dd4cf

java.lang.ArrayIndexOutOfBoundsException: 1
	at org.codehaus.groovy.runtime.dgmimpl.arrays.ObjectArrayGetAtMetaMethod.invoke(ObjectArrayGetAtMetaMethod.java:41)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
	at org.codehaus.groovy.runtime.callsite.PojoMetaClassSite.call(PojoMetaClassSite.java:47)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.getArray(DefaultInvoker.java:57)
	at com.cloudbees.groovy.cps.impl.ArrayAccessBlock.rawGet(ArrayAccessBlock.java:21)
	at com.openshift.jenkins.plugins.OpenShiftDSL.splitNames(jar:file:/var/lib/jenkins/plugins/openshift-client/WEB-INF/lib/openshift-client.jar!/com/openshift/jenkins/plugins/OpenShiftDSL.groovy:447)
	at com.openshift.jenkins.plugins.OpenShiftDSL$OpenShiftResourceSelector.startBuild(jar:file:/var/lib/jenkins/plugins/openshift-client/WEB-INF/lib/openshift-client.jar!/com/openshift/jenkins/plugins/OpenShiftDSL.groovy:1444)
	at buildInOpenshift.call(/data/jenkins-jobs/Virtual Assistant DHL Express/jobs/dhl-express-pipeline/builds/43/libs/Openshift pipeline library/vars/buildInOpenshift.groovy:6)

**Comment by gabemontero** [comment]
Needed an extra array len check ... should have fix up fairly quickly.  This path is one affected by 3.10 API changes with `-o name` processing, so we don't see this problem on newer level.

The additional array check should default to the older path which applies in envs like the 3.6 usage noted here.

**Comment by gabemontero** [comment]
Our newer images will have the newer `oc` so am not worried about the 3.10 image, which was the first to have v1.0.12 of the plugin.

**Comment by gabemontero** [comment]
v 1.0.13 of the client plugin has been initiated .. it contains the commits intended to fix this

**Comment by GolanTrevize10** [comment]
Thanks Gabe, I will try it and let you know
