### ISSUE TITLE
java.io.NotSerializableException Exception

### ISSUE THREAD

**Issue by aytuncbeken** [openshift/jenkins-client-plugin#171]
Hi

After upgrading to latest version 10.0.15, openshift.process command ( and apply ) started to have exception below and commands are not working.

java.io.NotSerializableException: com.openshift.jenkins.plugins.util.QuietTaskListenerFactory$QuietTaskListenerIH
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at hudson.remoting.UserRequest._serialize(UserRequest.java:264)
	at hudson.remoting.UserRequest.serialize(UserRequest.java:273)
Caused: java.io.IOException: Unable to serialize hudson.Launcher$RemoteLaunchCallable@48b885fd
	at hudson.remoting.UserRequest.serialize(UserRequest.java:275)
	at hudson.remoting.UserRequest.<init>(UserRequest.java:101)
	at hudson.remoting.Channel.call(Channel.java:953)
	at hudson.Launcher$RemoteLauncher.launch(Launcher.java:1058)
	at hudson.Launcher$ProcStarter.start(Launcher.java:454)
	at org.jenkinsci.plugins.durabletask.BourneShellScript.launchWithCookie(BourneShellScript.java:186)
	at org.jenkinsci.plugins.durabletask.FileMonitoringTask.launch(FileMonitoringTask.java:86)
	at com.openshift.jenkins.plugins.pipeline.OcAction$Execution.run(OcAction.java:226)
	at com.openshift.jenkins.plugins.pipeline.OcAction$Execution.run(OcAction.java:153)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:47)
	at hudson.security.ACL.impersonate(ACL.java:290)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

**Comment by aytuncbeken** [comment]
Pipeline Script is
openshift.withCluster('mycluster') {
                     openshift.verbose()
						
							openshift.withProject('myProject') {
							   openshift.process( 'mytemplate' )
							}
						
					}

**Comment by gabemontero** [comment]
Hello @aytuncbeken 

I just tried to reproduce with: 

```
openshift.withCluster('mycluster') {
    openshift.verbose()
	openshift.withProject('myproject') {
	   openshift.process('nginx-example')
	}
}
```

but it works for me.  The 'nginx-example' template is one I created in 'myproject' before launching jenkins.

So something else besides just the changing the jenkins client plugin to v1.0.15 is going on.

Could you provide some additional details, to see if I can reproduce this:
- are you running jenkins inside an openshift pod, or external to openshift?
- are you using the jenkins from the OpenShift Jenkins image, or have you manually installed the client plugin into your existing Jenkins?
- are you running this on the jenkins master, or an agent/slave node? ... given the presence of `at hudson.Launcher$RemoteLauncher.launch(Launcher.java:1058)` in the stack trace, I'm wondering if this is a remote/agent/slave scenario ... if so, are you using the k8s plugin, or some other cloud provider?

  I did try embedding the pipeline into a node('...') closure, but it still worked for me.
- how exactly did you create the template?
- is it possible the job run was resumed after a jenkins restart?
- can you provide the entire job run log in addition to the exception stack trace?

thanks

**Comment by aytuncbeken** [comment]
Hi @gabemontero 

You can find my answers below. Also I will try to give more information
Jenkins Version 2.138
Plugin Version 1.0.15

-> we were not having this problem before upgrade.
are you running jenkins inside an openshift pod, or external to openshift?
-> Jenkins running as a application in linux server which is external to openshift
are you using the jenkins from the OpenShift Jenkins image, or have you manually installed the client plugin into your existing Jenkins?
-> Installed Plugin from Jenkins Plugin Page, Jenkins is running on linux server.
are you running this on the jenkins master, or an agent/slave node? ... given the presence of at hudson.Launcher$RemoteLauncher.launch(Launcher.java:1058) in the stack trace, I'm wondering if this is a remote/agent/slave scenario ... if so, are you using the k8s plugin, or some other cloud provider?
-> This problem occurs when runs on slave, tested on master and works. Also tested slave for other plugins to see if any problem about the slave configuration. Other plugins works on slave well.
I did try embedding the pipeline into a node('...') closure, but it still worked for me.
-> Both tried in openshfit container node and jenkins dump slave, had error.
how exactly did you create the template?
-> It is not about the template, other commands using OAction ( I think) are also throwing exception
is it possible the job run was resumed after a jenkins restart?
-> Nope, I tried every possible situation for the build, before restart, after restart, after while of restart : ) 
can you provide the entire job run log in addition to the exception stack trace?
-> Sure log is below

Started by user AYTUNC BEKEN
Running in Durability level: MAX_SURVIVABILITY
Loading library PipelineExternalLib@master
Attempting to resolve master from remote references...
 > /usr/bin/git --version # timeout=10
using GIT_ASKPASS to set credentials 
 > /usr/bin/git ls-remote -h https://**************/git/scm/jenkinspipeline/pipelineexternallib.git # timeout=10
Found match: refs/heads/master revision 22345019a434b15b18622be5447bb65e754664eb
 > /usr/bin/git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > /usr/bin/git config remote.origin.url https://**************/git/scm/jenkinspipeline/pipelineexternallib.git # timeout=10
Fetching without tags
Fetching upstream changes from https://**************/git/scm/jenkinspipeline/pipelineexternallib.git
 > /usr/bin/git --version # timeout=10
using GIT_ASKPASS to set credentials 
 > /usr/bin/git fetch --no-tags --progress https://**************/git/scm/jenkinspipeline/pipelineexternallib.git +refs/heads/*:refs/remotes/origin/*
Checking out Revision 22345019a434b15b18622be5447bb65e754664eb (master)
 > /usr/bin/git config core.sparsecheckout # timeout=10
 > /usr/bin/git checkout -f 22345019a434b15b18622be5447bb65e754664eb
Commit message: "OpenShift yapısı jenkins plugin komutlarına alındı."
[Pipeline] node
Running on myNode in /data01/jenkins/workspace/Test_Jobs/test/git_test
[Pipeline] {
[Pipeline] echo

[Pipeline] _OcContextInit
[Pipeline] _OcContextInit
[Pipeline] _OcAction
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
java.io.NotSerializableException: com.openshift.jenkins.plugins.util.QuietTaskListenerFactory$QuietTaskListenerIH
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at hudson.remoting.UserRequest._serialize(UserRequest.java:264)
	at hudson.remoting.UserRequest.serialize(UserRequest.java:273)
Caused: java.io.IOException: Unable to serialize hudson.Launcher$RemoteLaunchCallable@57f7954e
	at hudson.remoting.UserRequest.serialize(UserRequest.java:275)
	at hudson.remoting.UserRequest.<init>(UserRequest.java:101)
	at hudson.remoting.Channel.call(Channel.java:953)
	at hudson.Launcher$RemoteLauncher.launch(Launcher.java:1058)
	at hudson.Launcher$ProcStarter.start(Launcher.java:454)
	at org.jenkinsci.plugins.durabletask.BourneShellScript.launchWithCookie(BourneShellScript.java:186)
	at org.jenkinsci.plugins.durabletask.FileMonitoringTask.launch(FileMonitoringTask.java:86)
	at com.openshift.jenkins.plugins.pipeline.OcAction$Execution.run(OcAction.java:226)
	at com.openshift.jenkins.plugins.pipeline.OcAction$Execution.run(OcAction.java:153)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:47)
	at hudson.security.ACL.impersonate(ACL.java:290)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Finished: FAILURE

**Comment by gabemontero** [comment]
OK that information helped progress things @aytuncbeken .... the jenkins version probably has some bearing here (we have not tested at that level yet) ... I'll see about adding that to the list.

On more follow up - when you upgraded to 1.0.15, do you remember what version you were at previously?  I only ask cause the change between 1.0.14 and 1.0.15 has nothing to do with this space.  But if you went from an older version, then I should widen the commits to investigate what the newer jenkins/remoting jar might be doing.

In addition to that, I started looking at the jenkins TaskListener we are proxying after my last comment here, and did see some hidden/old school serializablitity logic that we should pick up in our QuitetTaskListenerIH.  I've started working on a patch for that in the interim.

**Comment by gabemontero** [comment]
OK, I was able to reproduce when I ran on Jenkins 2.138 @aytuncbeken 

I'll start testing the QuietTaskListenerIH change I mentioned in https://github.com/openshift/jenkins-client-plugin/issues/171#issuecomment-413578230

I'll also do some quick examinations of earlier versions of the client plugin, just for curiosity.

**Comment by gabemontero** [comment]
Yep, I went back as far as v1.0.0 and the problem persists.  Bet a jenkins upgrade in conjunction with a client plugin one resulted in the problem arising.

**Comment by gabemontero** [comment]
I've been able to verify a fix ... will start the process of cutting a new client plugin release

**Comment by gabemontero** [comment]
I've initiated v1.0.16 at the jenkins update center with the commit from the referenced PR

**Comment by aytuncbeken** [comment]
Hi @gabemontero 

I am sorry did not responded to your comments on time. Thank you for your great support on this issue. I will wait for the new versiyon.

**Comment by gabemontero** [comment]
No worries @aytuncbeken , we got it sorted out

And for your info, the new 1.0.16 version is available at the jenkins update/download center, and our openshift / jenkins docker image is updated (though I know you are installing the plugin in an existing install).
