### ISSUE TITLE
Timeout/Retry not handled correctly

### ISSUE THREAD

**Issue by Xaseron** [openshift/jenkins-client-plugin#200]
If i run the following code it looks like the timeout cancels the oc command, but the wrong exception reaches the retry step and it retries the execution till the hard kill of timeout step is executed.
The retry step needs a *FlowInterruptedException* to abort the current build. But in my case only an *InterruptedException* is thrown.
Maybe the bug is more related to timeout/retry step interaction.

```
timeout(time: mergedArgs.timeoutInMinutes, unit: 'MINUTES') {
    for (selector in selectors) {
        retry(mergedArgs.numberOfRetries) {
            selector.narrow('dc')?.related('pods')?.untilEach {
                it.object()?.status?.containerStatuses?.every { container -> container.ready }
            }
        }
    }
```
Pipeline + Stacktrace
```
2018-11-12 15:23:18.559: Running watch closure body
[Pipeline] {
[Pipeline] _OcAction
[Pipeline] _OcAction
[Pipeline] _OcAction
[Pipeline] }
2018-11-12 15:23:55.517: Cancelling nested steps due to timeout
[Pipeline] // _OcWatch
[Pipeline] }
2018-11-12 15:23:55.524: ERROR: Execution failed
2018-11-12 15:23:55.524: java.lang.InterruptedException
2018-11-12 15:23:55.524: 	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014)
2018-11-12 15:23:55.524: 	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048)
2018-11-12 15:23:55.524: 	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
2018-11-12 15:23:55.524: 	at java.util.concurrent.ExecutorCompletionService.take(ExecutorCompletionService.java:193)
2018-11-12 15:23:55.524: 	at com.openshift.jenkins.plugins.util.ClientCommandRunner.run(ClientCommandRunner.java:184)
2018-11-12 15:23:55.524: 	at com.openshift.jenkins.plugins.pipeline.OcWatch$Execution.run(OcWatch.java:148)
2018-11-12 15:23:55.524: 	at com.openshift.jenkins.plugins.pipeline.OcWatch$Execution.run(OcWatch.java:75)
2018-11-12 15:23:55.524: 	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:47)
2018-11-12 15:23:55.524: 	at hudson.security.ACL.impersonate(ACL.java:290)
2018-11-12 15:23:55.524: 	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:44)
2018-11-12 15:23:55.524: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
2018-11-12 15:23:55.524: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2018-11-12 15:23:55.524: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
2018-11-12 15:23:55.524: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
2018-11-12 15:23:55.524: 	at java.lang.Thread.run(Thread.java:745)
2018-11-12 15:23:55.524: Retrying
[Pipeline] {
[Pipeline] _OcWatch
2018-11-12 15:23:55.958: Running watch closure body
[Pipeline] {
```

**Comment by gabemontero** [comment]
Interesting @Xaseron  .... I have not hunted for the implementation of `retry` but the doc at https://jenkins.io/doc/pipeline/steps/workflow-basic-steps/#retry-retry-the-body-up-to-n-times does not specify that the exception needs to be a certain type.

Also, if you look at the implemenation of org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution<T> 

at least at the version we are running with, there are no stipulation laid around this.  In fact the call to the run method is surrounded in a try/catch on the generic exception class, where on the exception, it calls

`getContext().onFailure(e);`

This definitely feels like an issue with the retry step to me.
