### ISSUE TITLE
Make declarative work

### ISSUE THREAD

**Issue by abergmeier** [openshift/jenkins-client-plugin#201]
What is currently blocking to get full declarative support working?
It feels strange to not be able to use declarative in 2019 due to this plugin.

**Comment by itewk** [comment]
So i discovered that 1.0.12 version of the plugin works with declarative pipelines but `1.0.22` does not. So i started with 1.0.22 and worked my way backwards installing different versions of the plugin and found that the newest version that worked with declarative pipelines is `1.0.16`. Everything above that, 1.0.17 and above, does not work, most give an error that looks like:

```
[BFA] Scanning build for known causes...
[BFA] No failure causes found
[BFA] Done. 0s
java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from 10.128.4.1/10.128.4.1:58840
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1741)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:357)
		at hudson.remoting.Channel$2.adapt(Channel.java:990)
		at hudson.remoting.Channel$2.adapt(Channel.java:986)
		at hudson.remoting.FutureAdapter.get(FutureAdapter.java:55)
		at com.openshift.jenkins.plugins.util.ClientCommandRunner.run(ClientCommandRunner.java:148)
		at com.openshift.jenkins.plugins.pipeline.OcAction$Execution.run(OcAction.java:198)
		at com.openshift.jenkins.plugins.pipeline.OcAction$Execution.run(OcAction.java:121)
		at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:47)
		at hudson.security.ACL.impersonate(ACL.java:290)
		at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:44)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
Caused: java.io.IOException: Cannot run program "oc" (in directory "/home/jenkins/workspace/yellowdog-cicd-ian/yellowdog-cicd-ian-vue-app-pipeline"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at hudson.Proc$LocalProc.<init>(Proc.java:249)
	at hudson.Proc$LocalProc.<init>(Proc.java:218)
	at com.openshift.jenkins.plugins.util.ClientCommandRunner$OcCallable.invoke(ClientCommandRunner.java:99)
	at com.openshift.jenkins.plugins.util.ClientCommandRunner$OcCallable.invoke(ClientCommandRunner.java:80)
	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:3085)
	at hudson.remoting.UserRequest.perform(UserRequest.java:212)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:369)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:93)
Caused: java.util.concurrent.ExecutionException
	at hudson.remoting.Channel$2.adapt(Channel.java:992)
	at hudson.remoting.Channel$2.adapt(Channel.java:986)
	at hudson.remoting.FutureAdapter.get(FutureAdapter.java:55)
	at com.openshift.jenkins.plugins.util.ClientCommandRunner.run(ClientCommandRunner.java:148)
	at com.openshift.jenkins.plugins.pipeline.OcAction$Execution.run(OcAction.java:198)
	at com.openshift.jenkins.plugins.pipeline.OcAction$Execution.run(OcAction.java:121)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:47)
	at hudson.security.ACL.impersonate(ACL.java:290)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Finished: FAILURE
```

which is strange because the /bin/oc definitely exists. My guess is that in the versions that are broken somehow this plugin is ignoring the `contianer()` statement and runniing on the wrong container in the pod, i *think* in the cases where it is broken it is running on the `jnlp` container rather then the specified container.

**Comment by itewk** [comment]
@gabemontero i dont think this should be closed. I have followed on the instrucitons on compatibility with declarative, but our pipeline still only works on 1.0.16 or 1.0.12, when i try it on 1.0.22 i get that error message. 

Sample pipeline here, at the `Build Image` step on 1.0.22 it fails, on 1.0.16 it works, and as far as I can tell we are following everything outlined in https://github.com/openshift/jenkins-client-plugin#compatibility-with-declarative-pipeline

```
def ciProject = 'yellowdog-cicd-ian'
def devProject = 'yellowdog-dev-ian'
def testProject = 'yellowdog-test-ian'
def prodProject = 'yellowdog-prod-ian'


pipeline {
    environment {
        PROJECT_NAME = 'vue-app'
        KUBERNETES_NAMESPACE = "${ciProject}"
    }
    agent {
        kubernetes {
          label "npm-${env.BUILD_ID}"
          defaultContainer 'jenkins-slave-npm'
          yaml """
apiVersion: v1
kind: Pod
metadata:
  labels:
    pod-template: jenkins-slave-npm
spec:
  containers:
  - name: jenkins-slave-npm
    image: docker-registry.default.svc:5000/yellowdog/jenkins-slave-npm
    tty: true
    env:
    - name: PATH
      value: "/home/jenkins/.npm-global/bin:/bin:/usr/bin:/usr/local/bin:/sbin:/usr/sbin:/usr/local/sbin:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.191.b12-0.el7_5.x86_64/jre/bin"
    command:
    - cat
"""
        }
    }
    stages {
        stage('Quality And Security') {
            parallel {
                stage('Dependency Check') {
                    steps {
                        container('jenkins-slave-npm') {
                            sh 'npm config set cache /tmp'
                            sh 'mkdir -p audit-reports'
                            sh 'npm install --global npm-audit-html npm-audit-ci-wrapper sonar-scanner'
                            sh 'npm audit --json | npm-audit-html -o audit-reports/npm-audit-report.html'
                            publishHTML(target: [
                                reportDir             : 'audit-reports',
                                reportFiles           : 'npm-audit-report.html',
                                reportName            : 'NPM Audit Report',
                                keepAll               : true,
                                alwaysLinkToLastBuild : true,
                                allowMissing          : true
                            ])
                            sh 'npm-audit-ci-wrapper -t high --ignore-dev-dependencies'
                        }
                    }
                }
                stage('Compile & Test') {
                    steps {
                        container('jenkins-slave-npm') {
                            sh 'npm --cache /tmp/npm-cache install'
                            sh 'npm --cache /tmp/npm-cache run test:unit'
                            sh 'npm --cache /tmp/npm-cache run build'
                            publishHTML(target: [
                                reportDir             : 'unit-test-reports',
                                reportFiles           : 'index.html',
                                reportName            : 'Jest Unit Test Report',
                                keepAll               : true,
                                alwaysLinkToLastBuild : true,
                                allowMissing          : true
                            ])
                            publishHTML(target: [
                                reportDir             : 'coverage/lcov-report',
                                reportFiles           : 'index.html',
                                reportName            : 'Jest Test Coverage Report',
                                keepAll               : true,
                                alwaysLinkToLastBuild : true,
                                allowMissing          : true
                            ])
                        }
                    }
                }
            }
        }
        stage('Build Image') {
            steps {
                container('jenkins-slave-npm') {
                    script {
                        openshift.withCluster() {
                            openshift.withProject(ciProject) {
                                openshift.selector('bc', 'vue-app').startBuild("--from-dir=dist/", '--wait')
                            }
                        }
                    }
                }
            }
        }
        stage('Promote to TEST') {
            steps {
                container('jenkins-slave-npm') {
                    script {
                        withEnv(['PATH=/bin:/usr/bin:/usr/local/bin:/sbin:/usr/sbin:/usr/local/sbin:$PATH']) {
                            openshift.withCluster() {
                                openshift.withProject(ciProject) {
                                    openshift.tag("vue-app:latest", "${testProject}/vue-app:latest")
                                }
                            }
                        }
                    }
                }
            }
        }
        stage('Promote to DEMO') {
            input {
                message "Promote service to DEMO environment?"
                ok "PROMOTE"
            }
            steps {
                container('jenkins-slave-npm') {
                    script {
                        withEnv(['PATH=/bin:/usr/bin:/usr/local/bin:/sbin:/usr/sbin:/usr/local/sbin:$PATH']) {
                            openshift.withCluster() {
                                openshift.withProject(ciProject) {
                                    openshift.tag("vue-app:latest", "${devProject}/vue-app:latest")
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
```

**Comment by gabemontero** [comment]
File a separate bugzilla @itewk as you have a much more specific use case then the generic claim here.  Plus it will get higher priority that way.

There must be some implementation difference between the `container` DSL step and the 

```
        pipeline {
            agent {
              node {
                // spin up a node.js slave pod to run this build on
                label 'nodejs'
              }
            }

```

style of leveraging agents.  Depending on how `container` from the k8s plugin works, we might be able to compensate with the new forms we've had to adopt from 1.0.17 forward.

**Comment by itewk** [comment]
@gabemontero will do. what is the right Bugzilla component to open issues for the plugins against? https://bugzilla.redhat.com/enter_bug.cgi?product=OpenShift%20Container%20Platform? If so, which component?

**Comment by gabemontero** [comment]
On Thu, Dec 6, 2018 at 3:09 PM Ian Tewksbury <notifications@github.com>
wrote:

> @gabemontero <https://github.com/gabemontero> will do. what is the right
> Bugzilla component to open issues for the plugins against?
> https://bugzilla.redhat.com/enter_bug.cgi?product=OpenShift%20Container%20Platform?
> If so, which component?
>
Use the same values that are set for your other bugzilla.
