### ISSUE TITLE
Cannot invoke method getServerUrl() on null object when moving code into Jenkins shared library

### ISSUE THREAD

**Issue by racodond** [openshift/jenkins-client-plugin#206]
Hi,

In my Jenkinsfile, the following piece of code works fine:

```
openshift.withCluster('my-cluster') {
  openshift.withProject('my-project') {
    stage('Build Docker Images') {
      def build = openshift.selector('bc/mybc').startBuild()
      timeout(30) {
        build.untilEach(1) {
          echo "Waiting for ${it.object().metadata.name} to complete..."
          return it.object().status.phase == "Complete"
        }
     }
  }
}
```

I create a function that I put in my Jenkins shared library: vars/myopenshift
```
def buildAndWaitForCompletion(build_config) {
  def build = openshift.selector('bc/' + build_config).startBuild()
    timeout(30) {
      build.untilEach(1) {
        echo "Waiting for ${it.object().metadata.name} to complete..."
        return it.object().status.phase == "Complete"
      }
    }
  }
}
```
Then I modify my Jenkinsfile as follow:
```
openshift.withCluster('my-cluster') {
  openshift.withProject('my-project') {
    stage('Build Docker Images') {
      buildAndWaitForCompletion('mybc')
     }
  }
}
```

But I get:
```
java.lang.NullPointerException: Cannot invoke method getServerUrl() on null object
	at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:91)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:48)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:35)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.methodCall(DefaultInvoker.java:19)
	at com.openshift.jenkins.plugins.OpenShiftDSL.buildCommonArgs(jar:file:/var/lib/jenkins/plugins/openshift-client/WEB-INF/lib/openshift-client.jar!/com/openshift/jenkins/plugins/OpenShiftDSL.groovy:482)
	at com.openshift.jenkins.plugins.OpenShiftDSL.buildCommonArgs(jar:file:/var/lib/jenkins/plugins/openshift-client/WEB-INF/lib/openshift-client.jar!/com/openshift/jenkins/plugins/OpenShiftDSL.groovy:429)
	at com.openshift.jenkins.plugins.OpenShiftDSL$OpenShiftResourceSelector.startBuild(jar:file:/var/lib/jenkins/plugins/openshift-client/WEB-INF/lib/openshift-client.jar!/com/openshift/jenkins/plugins/OpenShiftDSL.groovy:1535)
	at myopenshift.buildAndWaitForCompletion(/var/lib/jenkins/jobs/jenkins-openshift/branches/feature-m.dm7rk7uc39qc.e-library/builds/12/libs/jenkins-pipeline-library/vars/myopenshift.groovy:2)
	at WorkflowScript.run(WorkflowScript:28)
	at ___cps.transform___(Native Method)
	at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:57)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:109)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixName(FunctionCallBlock.java:77)
	at sun.reflect.GeneratedMethodAccessor325.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)
	at com.cloudbees.groovy.cps.Next.step(Next.java:83)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:174)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:163)
	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:122)
	at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:261)
	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:163)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:19)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable$1.call(SandboxContinuable.java:35)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable$1.call(SandboxContinuable.java:32)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.GroovySandbox.runInSandbox(GroovySandbox.java:108)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:32)
	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:174)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:331)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$100(CpsThreadGroup.java:82)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:243)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:231)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:131)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

What am I missing?

Thanks for your help!

David

**Comment by racodond** [comment]
Hi guys,

Any feedback on this matter?

Thank you!

David

**Comment by gabemontero** [comment]
I suspect it stems from the fact that this plugin is a Jenkins Global Variable (it was modeled off of their docker plugin way back when in the early pipeline days) ... see https://jenkins.io/doc/book/pipeline/getting-started/#global-variable-reference 

that exception stems from the fact that the state from your `openshift.withCluster` call must have been lost as you entered the shared lib.

From tangential observation (see the pain points with declarative pipeline we have because of https://issues.jenkins-ci.org/browse/JENKINS-42360 ), the global variables might be "losing favor".

We haven't done anything with shred libs, nor have plans to given current priorities.

Maybe the above gives you some sort of inkling of how to investigate further.  Otherwise, apologies, we won't be diving into this space.

**Comment by racodond** [comment]
OK. Thanks for your feedback.

**Comment by TomSchmitz** [comment]
Ich bin bis 11.02.2019 abwesend.
I am out of the office until 11.02.2019.

Ich werde Ihre Nachricht nach meiner Rückkehr beantworten.

In dringenden Fällen wenden Sie sich bitte an Frank Becker (AC-6606)


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re:
[openshift/jenkins-client-plugin] Cannot invoke method getServerUrl() on
null object when moving code into Jenkins shared library (#206)" gesendet
am 31.01.2019 18:22:32.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während
diese Person abwesend ist.

**Comment by maikebertpsc** [comment]
I am a little bit surprised that this problem is not having priority.
How should somebody, who needs to re-use such code in several pipelines, stay DRY without using shared libraries?

**Comment by ThomVivet** [comment]
If you pass the openshift global to the called functions, it should work:
```
openshift.withCluster('my-cluster') {
  openshift.withProject('my-project') {
    stage('Build Docker Images') {
      buildAndWaitForCompletion(openshift, 'mybc')
     }
  }
}
```

**Comment by maikebertpsc** [comment]
I tried your suggestion, but the result is still the same.

Maybe because I have to call openshift.withCluster and openshift.withProject within my shared library method?

**Comment by maikebertpsc** [comment]
Thanks, this approach actually worked.

**Comment by saikirandusari** [comment]
@maikebertpsc I did encounter with the same issue in the past and have added below to all my shared libraries 

OpenShift.withCluster() { openshift.withProjet(‘project’) {
.....
}}
