### ISSUE TITLE
java.io.IOException: Cannot run program "/usr/bin/oc" (in version 1.0.23 of plugin)

### ISSUE THREAD

**Issue by grdryn** [openshift/jenkins-client-plugin#211]
Hi!

I've got an agent image, where `oc` is installed to `/usr/local/bin/oc` (note, not `/usr/bin/oc` as the error suggests), here's where it gets installed: https://github.com/feedhenry/wendy-jenkins-s2i-configuration/blob/master/agent-base-centos7/Dockerfile#L18

I updated to version 1.0.23 of this plugin (I don't think I was on 1.0.22 before that, I could have been 2 or 3 versions back), and now I see the following error output in a pipeline:

```
java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from 172.54.132.1/172.54.132.1:49064
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1741)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:357)
		at hudson.remoting.Channel.call(Channel.java:955)
		at hudson.Launcher$RemoteLauncher.launch(Launcher.java:1058)
		at hudson.Launcher$ProcStarter.start(Launcher.java:454)
		at com.openshift.jenkins.plugins.pipeline.OcAction$Execution.run(OcAction.java:196)
		at com.openshift.jenkins.plugins.pipeline.OcAction$Execution.run(OcAction.java:128)
		at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:47)
		at hudson.security.ACL.impersonate(ACL.java:290)
		at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:44)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
Caused: java.io.IOException: Cannot run program "/usr/bin/oc" (in directory "/tmp/workspace/jenkins_cd_on_new_upstream__image"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at hudson.Proc$LocalProc.<init>(Proc.java:249)
	at hudson.Proc$LocalProc.<init>(Proc.java:218)
	at hudson.Launcher$LocalLauncher.launch(Launcher.java:935)
	at hudson.Launcher$ProcStarter.start(Launcher.java:454)
	at hudson.Launcher$RemoteLaunchCallable.call(Launcher.java:1312)
	at hudson.Launcher$RemoteLaunchCallable.call(Launcher.java:1265)
	at hudson.remoting.UserRequest.perform(UserRequest.java:212)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:369)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:93)
	at java.lang.Thread.run(Thread.java:748)
```

@gabemontero do you think that this could be related to your changes in https://github.com/jenkinsci/openshift-client-plugin/commit/861cb2c1cf939696a75c39568d8a9c5fea999bdb (and if so, is it a bug or should I need to change my oc path)? It seems like the referenced section in `OcAction.java` in the error output was changed as part of that at least.

I did some brief digging to see if I could understand better, and I see that I've got a `/usr/bin/ocs` from the `cscope` package. I'm not sure if that could be causing [this `new File(dir, "oc").canExecute()`](https://github.com/openshift/jenkins-client-plugin/blob/master/src/main/java/com/openshift/jenkins/plugins/util/ClientCommandBuilder.java#L45) to somehow cause a match for `/usr/bin/` (although I'd be surprised if that was the case).

Also, I don't see [this warning log message](https://github.com/openshift/jenkins-client-plugin/blob/master/src/main/java/com/openshift/jenkins/plugins/util/ClientCommandBuilder.java#L41) either in the job output or the jenkins master pod logs.

**Comment by gabemontero** [comment]
Yeah @grdryn we have had to rework processing launching to fix various scenarios.  Aside from the commit you noted, a couple of commits back at https://github.com/openshift/jenkins-client-plugin/commit/244c3fc893f3b6a0566a1fafb06b9d446f3cc553#diff-dcd07aa221d2ea9075cd77e4c245364a (which was a version or two before 1.0.23) is where we had to start inspecting the path as a result of moving off of durable task / jenkins bourne shell.

I agree with you that I don't see `/usr/bin/ocs` having a bearing here.  I suspect either 
a) it is not seeing `/usr/local/bin` when inspecting that `PATH` env var it receives from Jenkins (where Jenkins is not providing the plugin what you would expect)
b) or the code at https://github.com/openshift/jenkins-client-plugin/blob/master/src/main/java/com/openshift/jenkins/plugins/util/ClientCommandBuilder.java#L51-L54 perhaps `command[0]` has an `oc` with dirs already in it or something along those lines .... maybe `oc` is in `command[1]` for some weird reason, and we are not hitting the `.equals("oc") check

But some debug in your env could help expedite.

a) could you print the `PATH` env in your pipeline and provide its contents here?  it could be useful for unit testing?
b) if I provided you a path with prints in that function, could you run with it?

**Comment by grdryn** [comment]
Thanks @gabemontero!

I've created a simpler reproducer than the pipeline that I experienced this in:

<details>
<pre>
pipeline {
    agent {
        node {
            label 'jenkins-tools'
        }
    }

    stages {
        stage('wtf') {
            steps {
                script {
                    openshift.withCluster('<scrubbed>') {
                        openshift.withProject(params.stageProject) {
                            echo "Hello from project ${openshift.project()} in cluster ${openshift.cluster()}"
                            sh "ls -lh /usr/local/bin/oc"
                            openshift.selector( 'deploymentconfig/jenkins' ).describe()
                        }
                    }
                }
            }
        }
    }
}
</pre>
</details>
<br />
Here's the output that it fails with. As you can see, right before I call `openshift.selector( 'deploymentconfig/jenkins' ).describe()`, I ensure that there's an executable binary at `/usr/local/bin/oc`, but it doesn't seem to be able to find it:

<br />

<details>
<pre>
Started by user gryan
Running in Durability level: MAX_SURVIVABILITY
[Pipeline] node
Still waiting to schedule task
All nodes of label ‘jenkins-tools’ are offline

Agent jenkins-agent-jenkins-tools-1m2kw is provisioned from template Kubernetes Pod Template
Agent specification [Kubernetes Pod Template] (jenkins-tools jenkins tools openshift): 
* [jnlp] docker-registry.default.svc:5000/rhmap-jenkins/jenkins-agent-jenkins-tools

Running on jenkins-agent-jenkins-tools-1m2kw in /tmp/workspace/test-openshift-client-plugin
[Pipeline] {
[Pipeline] stage
[Pipeline] { (wtf)
[Pipeline] script
[Pipeline] {

[Pipeline] echo

[Pipeline] _OcContextInit

[Pipeline] _OcContextInit
[Pipeline] echo
Hello from project <scrubbed> in cluster <scrubbed>
[Pipeline] sh
[test-openshift-client-plugin] Running shell script
+ ls -lh /usr/local/bin/oc
-rwxr-xr-x. 1 root 1003 191M Nov 29  2017 /usr/local/bin/oc
[Pipeline] _OcAction
Environment Variables for launching 'oc'
examining path /opt/rh/rh-git29/root/usr/bin for presence of oc
/opt/rh/rh-git29/root/usr/bin/oc exists: false
/opt/rh/rh-git29/root/usr/bin/oc can execute: false
/opt/rh/rh-git29/root/usr/bin/oc.exe can execute: false
/opt/rh/rh-git29/root/usr/bin/oc.exe exists: false
examining path /usr/local/sbin for presence of oc
/usr/local/sbin/oc exists: false
/usr/local/sbin/oc can execute: false
/usr/local/sbin/oc.exe can execute: false
/usr/local/sbin/oc.exe exists: false
examining path /usr/local/bin for presence of oc
/usr/local/bin/oc exists: false
/usr/local/bin/oc can execute: false
/usr/local/bin/oc.exe can execute: false
/usr/local/bin/oc.exe exists: false
examining path /usr/sbin for presence of oc
/usr/sbin/oc exists: false
/usr/sbin/oc can execute: false
/usr/sbin/oc.exe can execute: false
/usr/sbin/oc.exe exists: false
examining path /usr/bin for presence of oc
/usr/bin/oc exists: true
/usr/bin/oc can execute: true
/usr/bin/oc.exe can execute: false
/usr/bin/oc.exe exists: false
using dir /bin
oc command came in as oc
switched oc command to /usr/bin/oc
[Pipeline] }
[Pipeline] // script
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from 172.54.64.1/172.54.64.1:45114
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1741)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:357)
		at hudson.remoting.Channel.call(Channel.java:955)
		at hudson.Launcher$RemoteLauncher.launch(Launcher.java:1058)
		at hudson.Launcher$ProcStarter.start(Launcher.java:454)
		at com.openshift.jenkins.plugins.pipeline.OcAction$Execution.run(OcAction.java:181)
		at com.openshift.jenkins.plugins.pipeline.OcAction$Execution.run(OcAction.java:125)
		at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:47)
		at hudson.security.ACL.impersonate(ACL.java:290)
		at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:44)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
Caused: java.io.IOException: Cannot run program "/usr/bin/oc" (in directory "/tmp/workspace/test-openshift-client-plugin"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at hudson.Proc$LocalProc.<init>(Proc.java:249)
	at hudson.Proc$LocalProc.<init>(Proc.java:218)
	at hudson.Launcher$LocalLauncher.launch(Launcher.java:935)
	at hudson.Launcher$ProcStarter.start(Launcher.java:454)
	at hudson.Launcher$RemoteLaunchCallable.call(Launcher.java:1312)
	at hudson.Launcher$RemoteLaunchCallable.call(Launcher.java:1265)
	at hudson.remoting.UserRequest.perform(UserRequest.java:212)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:369)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:93)
	at java.lang.Thread.run(Thread.java:748)
Finished: FAILURE
</pre>
</details>

<br />

* Is it definitely checking for the binary on the agent, or could it be checking on the master?
* Does it expect a particular version (or version within a range) of oc?

**Comment by gabemontero** [comment]
Yep, it must be checking on the master @grdryn ... and now that I think about, I've realized that before about the run() methods for OcAction and OcWatch.

Some of the churn here stems from the couple of switches in process launching we've done starting with v1.0.17.  As I've switch back to more of a pre v1.0.17 model with v1.0.23 (minus the use of durable task plugin and the bourne/window shells that ultimately were untenable for the multitude of oc uses), we are now off of direct use of Proc.LocalProc and ProcessBuilder and back to the Jenkins libs re: Launcher.ProcStarter.

As such, I'm thinking ClientCommandBuilder.fixPathInCommandArray() a) is no longer needed, b) when it was needed, the path was such that it was being called on the agent when need be.

Give this one (with those calls commented out) a try:
[client-plugin-gerard-2.zip](https://github.com/openshift/jenkins-client-plugin/files/2799679/client-plugin-gerard-2.zip)

**Comment by grdryn** [comment]
> Give this one (with those calls commented out) a try:
> client-plugin-gerard-2.zip

@gabemontero this one was successful! :+1: Thanks! :100:

**Comment by gabemontero** [comment]
v1.0.24 of this plugin has been initiated at the update center

I'll update the jenkins image once your sec advisory PR dodges enough flakes to pass @grdryn
