### ISSUE TITLE
watch closure returns false even if the container status is ready

### ISSUE THREAD

**Issue by Xaseron** [openshift/jenkins-client-plugin#222]
The watch closure returns always false even though the containers are in the ready state.
The pipeline only continues when when the timeout kills the watch closure and it gets invoked again.
The runtime of my pipeline increased from 17 minutes to 52 minutes from 1.0.23.

code:
```
                    timeout(time: mergedArgs.timeoutInMinutes, unit: 'MINUTES') {
                        for (selector in selectors) {
                            retry(mergedArgs.numberOfRetries) {
                                selector.narrow('dc')?.related('pods')?.untilEach {
                                    it.object()?.status?.containerStatuses?.every { container -> container.ready }
                                }
                            }
                        }
                    }
```

log:
```
2019-01-30 12:38:06.673: Entering watch
2019-01-30 12:38:06.694: Running watch closure body
[Pipeline] {
[Pipeline] _OcAction
[Pipeline] _OcAction
[Pipeline] _OcAction
[Pipeline] _OcAction
[Pipeline] _OcAction
[Pipeline] }
2019-01-30 12:38:11.681: watch closure returned false
2019-01-30 12:38:11.682: Checking watch output and running watch closure again in 300ms having processed 0 bytes of watch output so far
2019-01-30 12:38:14.869: Running watch closure body
[Pipeline] {
[Pipeline] _OcAction
[Pipeline] _OcAction
[Pipeline] _OcAction
[Pipeline] }
2019-01-30 12:38:16.652: watch closure returned false
2019-01-30 12:38:16.652: Checking watch output and running watch closure again in 300ms having processed 40 bytes of watch output so far
2019-01-30 12:38:16.952: Running watch closure body
[Pipeline] {
[Pipeline] _OcAction
[Pipeline] _OcAction
[Pipeline] _OcAction
[Pipeline] }
2019-01-30 12:38:18.730: watch closure returned false
2019-01-30 12:38:18.730: Checking watch output and running watch closure again in 360ms having processed 40 bytes of watch output so far
2019-01-30 12:38:19.090: Running watch closure body
[Pipeline] {
[Pipeline] _OcAction
[Pipeline] _OcAction
[Pipeline] _OcAction
[Pipeline] }
2019-01-30 12:38:20.863: watch closure returned false
2019-01-30 12:38:20.864: Checking watch output and running watch closure again in 432ms having processed 80 bytes of watch output so far
2019-01-30 12:38:21.296: Running watch closure body
[Pipeline] {
[Pipeline] _OcAction
[Pipeline] _OcAction
[Pipeline] _OcAction
[Pipeline] }
2019-01-30 12:38:23.052: watch closure returned false
2019-01-30 12:38:23.053: Checking watch output and running watch closure again in 518ms having processed 80 bytes of watch output so far
2019-01-30 12:38:23.571: Running watch closure body
[Pipeline] {
[Pipeline] _OcAction
[Pipeline] _OcAction
[Pipeline] _OcAction
[Pipeline] }
2019-01-30 12:38:25.349: watch closure returned false
2019-01-30 12:38:25.349: Checking watch output and running watch closure again in 621ms having processed 80 bytes of watch output so far
2019-01-30 12:38:25.971: Running watch closure body
[Pipeline] {
[Pipeline] _OcAction
[Pipeline] _OcAction
[Pipeline] _OcAction
[Pipeline] }
2019-01-30 12:38:27.755: watch closure returned false
2019-01-30 12:38:27.755: Checking watch output and running watch closure again in 745ms having processed 80 bytes of watch output so far
2019-01-30 12:38:28.501: Running watch closure body
[Pipeline] {
[Pipeline] _OcAction
[Pipeline] _OcAction
[Pipeline] _OcAction
[Pipeline] }
2019-01-30 12:38:30.282: watch closure returned false
2019-01-30 12:38:30.282: Checking watch output and running watch closure again in 894ms having processed 80 bytes of watch output so far
2019-01-30 12:38:31.177: Running watch closure body
[Pipeline] {
[Pipeline] _OcAction
[Pipeline] _OcAction
[Pipeline] _OcAction
[Pipeline] }
2019-01-30 12:38:32.955: watch closure returned false
2019-01-30 12:38:32.955: Checking watch output and running watch closure again in 1072ms having processed 80 bytes of watch output so far
2019-01-30 12:38:34.027: Running watch closure body
[Pipeline] {
[Pipeline] _OcAction
[Pipeline] _OcAction
[Pipeline] _OcAction
[Pipeline] }
2019-01-30 12:38:35.800: watch closure returned false
2019-01-30 12:38:35.800: Checking watch output and running watch closure again in 1286ms having processed 80 bytes of watch output so far
2019-01-30 12:38:37.087: Running watch closure body
[Pipeline] {
[Pipeline] _OcAction
[Pipeline] _OcAction
[Pipeline] _OcAction
[Pipeline] }
2019-01-30 12:38:38.869: watch closure returned false
2019-01-30 12:38:38.870: Checking watch output and running watch closure again in 1543ms having processed 80 bytes of watch output so far
2019-01-30 12:38:40.413: Running watch closure body
[Pipeline] {
[Pipeline] _OcAction
[Pipeline] _OcAction
[Pipeline] _OcAction
[Pipeline] }
2019-01-30 12:38:42.167: watch closure returned false
2019-01-30 12:38:42.167: Checking watch output and running watch closure again in 1851ms having processed 80 bytes of watch output so far
2019-01-30 12:38:44.018: Running watch closure body
[Pipeline] {
[Pipeline] _OcAction
[Pipeline] _OcAction
[Pipeline] _OcAction
[Pipeline] }
2019-01-30 12:38:45.770: watch closure returned false
2019-01-30 12:38:45.770: Checking watch output and running watch closure again in 2221ms having processed 80 bytes of watch output so far
2019-01-30 12:38:47.991: Running watch closure body
[Pipeline] {
[Pipeline] _OcAction
[Pipeline] _OcAction
[Pipeline] _OcAction
[Pipeline] }
2019-01-30 12:38:49.745: watch closure returned false
2019-01-30 12:38:49.746: Checking watch output and running watch closure again in 2665ms having processed 80 bytes of watch output so far
2019-01-30 12:38:52.411: Running watch closure body
[Pipeline] {
[Pipeline] _OcAction
[Pipeline] _OcAction
[Pipeline] _OcAction
[Pipeline] }
2019-01-30 12:38:54.180: watch closure returned false
2019-01-30 12:38:54.180: Checking watch output and running watch closure again in 3198ms having processed 80 bytes of watch output so far
2019-01-30 12:38:57.379: Running watch closure body
[Pipeline] {
[Pipeline] _OcAction
[Pipeline] _OcAction
[Pipeline] _OcAction
[Pipeline] }
2019-01-30 12:38:59.172: watch closure returned false
2019-01-30 12:38:59.172: Checking watch output and running watch closure again in 3837ms having processed 80 bytes of watch output so far
2019-01-30 12:39:03.009: Running watch closure body
[Pipeline] {
[Pipeline] _OcAction
[Pipeline] _OcAction
[Pipeline] _OcAction
[Pipeline] }
2019-01-30 12:39:04.774: watch closure returned false
2019-01-30 12:39:04.775: Checking watch output and running watch closure again in 4604ms having processed 80 bytes of watch output so far
2019-01-30 12:39:09.379: Running watch closure body
[Pipeline] {
[Pipeline] _OcAction
[Pipeline] _OcAction
[Pipeline] _OcAction
[Pipeline] }
2019-01-30 12:39:11.177: watch closure returned false
2019-01-30 12:39:11.178: Checking watch output and running watch closure again in 5524ms having processed 80 bytes of watch output so far
2019-01-30 12:39:16.702: Running watch closure body
[Pipeline] {
[Pipeline] _OcAction
[Pipeline] _OcAction
[Pipeline] _OcAction
[Pipeline] }
2019-01-30 12:39:18.511: watch closure returned false
2019-01-30 12:39:18.512: Checking watch output and running watch closure again in 6628ms having processed 80 bytes of watch output so far
2019-01-30 12:39:25.140: Running watch closure body
[Pipeline] {
[Pipeline] _OcAction
[Pipeline] _OcAction
[Pipeline] _OcAction
[Pipeline] }
2019-01-30 12:39:26.927: watch closure returned false
2019-01-30 12:39:26.928: Checking watch output and running watch closure again in 7953ms having processed 80 bytes of watch output so far
2019-01-30 12:39:34.881: Running watch closure body
[Pipeline] {
[Pipeline] _OcAction
[Pipeline] _OcAction
[Pipeline] _OcAction
[Pipeline] }
2019-01-30 12:39:36.676: watch closure returned false
2019-01-30 12:39:36.676: Checking watch output and running watch closure again in 9543ms having processed 80 bytes of watch output so far
2019-01-30 12:39:46.219: Running watch closure body
[Pipeline] {
[Pipeline] _OcAction
[Pipeline] _OcAction
[Pipeline] _OcAction
[Pipeline] }
2019-01-30 12:39:48.015: watch closure returned false
2019-01-30 12:39:48.015: Checking watch output and running watch closure again in 11451ms having processed 80 bytes of watch output so far
2019-01-30 12:39:59.466: Running watch closure body
[Pipeline] {
[Pipeline] _OcAction
[Pipeline] _OcAction
[Pipeline] _OcAction
[Pipeline] }
2019-01-30 12:40:01.342: watch closure returned false
2019-01-30 12:40:01.343: Checking watch output and running watch closure again in 11451ms having processed 80 bytes of watch output so far
2019-01-30 12:40:12.794: Running watch closure body
[Pipeline] {
[Pipeline] _OcAction
[Pipeline] _OcAction
[Pipeline] _OcAction
[Pipeline] }
2019-01-30 12:40:14.580: watch closure returned false
2019-01-30 12:40:14.580: Checking watch output and running watch closure again in 11451ms having processed 80 bytes of watch output so far
2019-01-30 12:40:26.031: Running watch closure body
[Pipeline] {
[Pipeline] _OcAction
[Pipeline] _OcAction
[Pipeline] _OcAction
[Pipeline] }
2019-01-30 12:40:27.838: watch closure returned false
2019-01-30 12:40:27.838: Checking watch output and running watch closure again in 11451ms having processed 80 bytes of watch output so far
2019-01-30 12:47:07.153: Cancelling nested steps due to timeout
[Pipeline] // _OcWatch
[Pipeline] }
2019-01-30 12:47:07.225: ERROR: Execution failed
2019-01-30 12:47:07.226: java.lang.InterruptedException
2019-01-30 12:47:07.226: 	at java.lang.Object.wait(Native Method)
2019-01-30 12:47:07.226: 	at java.lang.Object.wait(Object.java:502)
2019-01-30 12:47:07.226: 	at java.lang.UNIXProcess.waitFor(UNIXProcess.java:396)
2019-01-30 12:47:07.226: 	at hudson.Proc$LocalProc.join(Proc.java:324)
2019-01-30 12:47:07.226: 	at hudson.Launcher$ProcStarter.join(Launcher.java:480)
2019-01-30 12:47:07.226: 	at com.openshift.jenkins.plugins.pipeline.OcWatch$Execution.run(OcWatch.java:196)
2019-01-30 12:47:07.226: 	at com.openshift.jenkins.plugins.pipeline.OcWatch$Execution.run(OcWatch.java:76)
2019-01-30 12:47:07.226: 	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:47)
2019-01-30 12:47:07.226: 	at hudson.security.ACL.impersonate(ACL.java:290)
2019-01-30 12:47:07.226: 	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:44)
2019-01-30 12:47:07.226: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
2019-01-30 12:47:07.226: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2019-01-30 12:47:07.226: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
2019-01-30 12:47:07.226: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
2019-01-30 12:47:07.226: 	at java.lang.Thread.run(Thread.java:745)
2019-01-30 12:47:07.226: Retrying
[Pipeline] {
[Pipeline] _OcWatch
2019-01-30 12:47:07.301: Entering watch
2019-01-30 12:47:07.315: Running watch closure body
[Pipeline] {
[Pipeline] _OcAction
[Pipeline] _OcAction
[Pipeline] _OcAction
[Pipeline] }
2019-01-30 12:47:09.911: 
2019-01-30 12:47:09.911: watch closure returned true; terminating watch
```

**Comment by schdief** [comment]
would be great to get this solved, we are fighting this problem too!

**Comment by TomSchmitz** [comment]
Ich bin bis 11.02.2019 abwesend.
I am out of the office until 11.02.2019.

Ich werde Ihre Nachricht nach meiner Rückkehr beantworten.

In dringenden Fällen wenden Sie sich bitte an Frank Becker (AC-6606)


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re:
[openshift/jenkins-client-plugin] watch closure returns false even if the
container status is ready (#222)" gesendet am 01.02.2019 10:22:56.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während
diese Person abwesend ist.

**Comment by gabemontero** [comment]
@Xaseron or @schdief 

unfortunately I'm going to need a repro from one of you with openshift.verbose(true) called prior to the `watch` or `untilEach` closures.

I'm not seeing the problem you noted with 
```
selector.narrow('dc')?.related('pods')?.untilEach {
       it.object()?.status?.containerStatuses?.every { container -> container.ready }
 }
```

when I go through various rollouts / manual deployment triggering

Based on logs provided, we are calling the watch, so the `oc` invocation should be occurring

if ` it.object()?.status?.containerStatuses?.every { container -> container.ready }` is returning false when it shouldn't, that on the surface would seem beyond the changes between the plugin versions noted.

With verbose on, we should see all the `oc` request and response data, and see why it is returning false.

**Comment by Xaseron** [comment]
The Response gets truncated :-(
I0214 14:01:01.664839    6331 request.go:897] Response Body: {"kind":"Pod","apiVersion":"v1","metadata":{"name":"petclinic-functional-master-1-nnbnc","generateName":"petclinic-functional-master-1-","namespace":"pep-tfcd-petclinic-uat","selfLink":"/api/v1/namespaces/pep-tfcd-petclinic-uat/pods/petclinic-functional-master-1-nnbnc","uid":"43502322-3058-11e9-be36-0050569a205e","resourceVersion":"234271810","creationTimestamp":"2019-02-14T12:58:45Z","labels":{"application":"petclinic-functional-master","branch":"master","color":"","commit":"abb6f58","deployment":"petclinic-functional-master-1","deploymentConfig":"petclinic-functional-master","deploymentconfig":"petclinic-functional-master","stack":"functional","template":"petclinic-functional-master","tpl":"petclinic"},"annotations":{"openshift.io/deployment-config.latest-version":"1","openshift.io/deployment-config.name":"petclinic-functional-master","openshift.io/deployment.name":"petclinic-functional-master-1","openshift.io/scc":"restricted"},"ownerReferences":[{"apiVersion":"v1","kind":"ReplicationController","name":"pe [truncated 3017 chars]

**Comment by gabemontero** [comment]
aahh... ok, looking at the k8s client go code, if verbosity is set to 10, it won't truncate, but his plugin's verbose option sets it at 8

@Xaseron or @schdief - can either of you run with a debug version of the plugin?

If so, the hpi file in this zip set's the `oc` verbose level to 10

[client-plugin-1.zip](https://github.com/openshift/jenkins-client-plugin/files/2870924/client-plugin-1.zip)

Get me job run with that and we'll go from there.

thanks

**Comment by vfreex** [comment]
@gabemontero Hi, we also met a similar issue with the recent version of the plugin. I've upgrade it to v1.0.27, but the issue persists.

What we are doing in the pipeline script is:

- Starting a OpenShift build from an existing Build Config.
- Using the watch closure to wait for it to complete

However, the watch closure returns false even the watched build is complete. It doesn't always happen, but frequently.

The Jenkins slave is running in an OpenShift pod (jnlp container) with Kubernetes plugin. The pipeline script is like:

``` groovy
            buildSelector = bc.startBuild()
            echo 'Waiting for the container build to start...'
            timeout(5) { // 5 min
              buildSelector.watch {
                return !(it.object().status.phase in ["New", "Pending", "Unknown"])
              }
            }
            // Ensure the build is stopped
            echo 'Waiting for the container build to be fully stopped...'
            timeout(15) { // 15 min
              buildSelector.watch {
                return it.object().status.phase != "Running"
              }
            }
```
When this issue happens, we get repeated logs like:

```
12:17:31 Checking watch output and running watch closure again in 3837ms having processed 1239 bytes of watch output so far
[Pipeline] }
12:17:43 Running watch closure body
[Pipeline] {
[Pipeline] readFile
[Pipeline] readFile
[Pipeline] _OcAction
12:17:44 watch closure returned false
12:17:44 Checking watch output and running watch closure again in 300ms having processed 1298 bytes of watch output so far
[Pipeline] }
```

Ps. Something strange is that the `reCheckSleep` value in the log goes larger and larger, then backs to 300ms, grows, and backs to 300ms again and again.

If I run `oc get build some-build -o json` on my local machine, `status.phase` is `Complete`. 

Until:

```
12:39:24 Cancelling nested steps due to timeout
```

**Comment by vfreex** [comment]
I am not sure if this is caused by the new way of launching `oc` using `Launcher.launch()`. I need more time to do some investigations (for example, enable the verbose mode and try older versions of the plugin). Do you have any clue about it?

**Comment by vfreex** [comment]
Another problem:
I created a test job to start and wait for a OpenShift build with verbose logging enabled in order to reproduce this issue. One interesting issue that I found is that after it prints `12:51:05 Checking watch output and running watch closure again in 1200ms having processed 964570 bytes of watch output so far`, the job seems to hang with no output. 10 minutes later, the job continues to output:

```
12:51:05 	Reference> {}
12:51:05 watch closure returned false
12:51:05 Checking watch output and running watch closure again in 1200ms having processed 964570 bytes of watch output so far
[Pipeline] }
14:01:30 Received verbose watch output>>>
14:01:30 I0307 04:48:45.733173     261 cached_discovery.go:104] returning cached discovery info from /home/jenkins/.kube/cache/discovery/172.56.0.1_443/servergroups.json
```

**Comment by vfreex** [comment]
Update: I added some logs to OcWatch, it seemed to me the return value of `proc.isAlive()` is unreliable. It returned false but the `oc` process is still watching. So the next line `proc.join()` will hangs until the `oc` process is actually stopped.

My patched code: https://github.com/openshift/jenkins-client-plugin/compare/master...vfreex:yuxzhu-test-1

Test run log: 
```
14:46:30 watch closure returned false
14:46:30 Checking watch output and running watch closure again in 1200ms having processed 1069695 bytes of watch output so far
[Pipeline] }
14:46:31 yuxzhu: After sleep.
14:46:31 yuxzhu: proc.isAlive() returned false. Joining the proc...
```

Back to the original problem of `watch closure always returns false`, my inference is: The watch closure keeps running is not because it returns false, but the watch step hangs on joining the watching `oc` process. That also explains why the `reCheckSleep` value gets reset frequently.

**Comment by gabemontero** [comment]
I plan on cutting v1.0.28 of this plugin either later today or early USEast time on Mar 14

**Comment by Xaseron** [comment]
Looks like this fixed our problem. Thanks for your help.
