### ISSUE TITLE
Unable to retrieve object markup with get; action failed

### ISSUE THREAD

**Issue by Joyce808** [openshift/jenkins-client-plugin#285]
Hello,

I am using jenkins-client-plugin version 1.0.18, Jenkins version 2.130 and openshift 3.9. 

We ran this exception when watching the pod status: 

```
latestDeploymentVersion is 46
[Pipeline] _OcAction
[Pipeline] _OcWatch
Running watch closure body
[Pipeline] {
[Pipeline] _OcAction
[Pipeline] _OcAction
[Pipeline] echo
pod: pods/app-46-qcvp6
[Pipeline] _OcAction
[Pipeline] echo
pod: pods/app-46-x8qh8
[Pipeline] _OcAction

watch closure threw an exception: "hudson.AbortException: Unable to retrieve object markup with get; action failed: {reference={}, err=Error in configuration: context was not found for specified context: dev/master-ocp-blah:8443/system:serviceaccount:app:jenkins
, verb=get, cmd=oc --server=https://console.ocp-blah:8443 --insecure-skip-tls-verify --namespace=app--token=XXXXX get pods/app-46-x8qh8 -o=json , out=, status=1}; Unable to retrieve object markup with get; action failed: {reference={}, err=Error in configuration: context was not found for specified context: dev/master-ocp-blah:8443/system:serviceaccount:app:jenkins
, verb=get, cmd=oc --server=https://console.ocp-blah:8443 --insecure-skip-tls-verify --namespace=dev--token=XXXXX get pods/app-46-x8qh8 -o=json , out=, status=1}".

Error in configuration: context was not found for specified context:dev/master-ocp-blah:8443/system:serviceaccount:app:jenkins
[Pipeline] }
[Pipeline] // _OcWatch
[Pipeline] }
[Pipeline] // script
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // withCredentials
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
hudson.AbortException: Unable to retrieve object markup with get; action failed: {reference={}, err=Error in configuration: context was not found for specified context: dev/master-ocp-blah:8443/system:serviceaccount:app:jenkins
, verb=get, cmd=oc --server=https://console.ocp-blah:8443 --insecure-skip-tls-verify --namespace=app --token=XXXXX get pods/app-46-x8qh8 -o=json , out=, status=1}
	at com.openshift.jenkins.plugins.pipeline.OcAction$OcActionResult.failIf(OcAction.java:87)
	at sun.reflect.GeneratedMethodAccessor586.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
	at org.codehaus.groovy.runtime.callsite.PojoMetaClassSite.call(PojoMetaClassSite.java:47)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.methodCall(DefaultInvoker.java:20)
	at com.openshift.jenkins.plugins.OpenShiftDSL$OpenShiftResourceSelector._asMarkup(jar:file:/var/jenkins_home/plugins/openshift-client/WEB-INF/lib/openshift-client.jar!/com/openshift/jenkins/plugins/OpenShiftDSL.groovy:1317)
	at com.openshift.jenkins.plugins.OpenShiftDSL$OpenShiftResourceSelector.asJson(jar:file:/var/jenkins_home/plugins/openshift-client/WEB-INF/lib/openshift-client.jar!/com/openshift/jenkins/plugins/OpenShiftDSL.groovy:1351)
	at com.openshift.jenkins.plugins.OpenShiftDSL$OpenShiftResourceSelector._asSingleMap(jar:file:/var/jenkins_home/plugins/openshift-client/WEB-INF/lib/openshift-client.jar!/com/openshift/jenkins/plugins/OpenShiftDSL.groovy:1367)
	at com.openshift.jenkins.plugins.OpenShiftDSL$OpenShiftResourceSelector.object(jar:file:/var/jenkins_home/plugins/openshift-client/WEB-INF/lib/openshift-client.jar!/com/openshift/jenkins/plugins/OpenShiftDSL.groovy:1388)
	at openshiftUtil.scalePods(/var/jenkins_home/jobs/app/branches/release.m8stf0/builds/32/libs/app-pipeline/vars/openshiftUtil.groovy:357)
	at com.openshift.jenkins.plugins.OpenShiftDSL$OpenShiftResourceSelector.untilEach(jar:file:/var/jenkins_home/plugins/openshift-client/WEB-INF/lib/openshift-client.jar!/com/openshift/jenkins/plugins/OpenShiftDSL.groovy:1285)
	at com.openshift.jenkins.plugins.OpenShiftDSL$OpenShiftResourceSelector.withEach(jar:file:/var/jenkins_home/plugins/openshift-client/WEB-INF/lib/openshift-client.jar!/com/openshift/jenkins/plugins/OpenShiftDSL.groovy:1561)
	at com.openshift.jenkins.plugins.OpenShiftDSL$OpenShiftResourceSelector.untilEach(jar:file:/var/jenkins_home/plugins/openshift-client/WEB-INF/lib/openshift-client.jar!/com/openshift/jenkins/plugins/OpenShiftDSL.groovy:1284)
	at com.openshift.jenkins.plugins.OpenShiftDSL$OpenShiftResourceSelector.watch(jar:file:/var/jenkins_home/plugins/openshift-client/WEB-INF/lib/openshift-client.jar!/com/openshift/jenkins/plugins/OpenShiftDSL.groovy:1253)
	at ___cps.transform___(Native Method)
	at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:57)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:109)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixArg(FunctionCallBlock.java:82)
	at sun.reflect.GeneratedMethodAccessor364.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:60)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:109)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixArg(FunctionCallBlock.java:82)
	at sun.reflect.GeneratedMethodAccessor364.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.LocalVariableBlock$LocalVariable.get(LocalVariableBlock.java:39)
	at com.cloudbees.groovy.cps.LValueBlock$GetAdapter.receive(LValueBlock.java:30)
	at com.cloudbees.groovy.cps.impl.LocalVariableBlock.evalLValue(LocalVariableBlock.java:28)
	at com.cloudbees.groovy.cps.LValueBlock$BlockImpl.eval(LValueBlock.java:55)
	at com.cloudbees.groovy.cps.LValueBlock.eval(LValueBlock.java:16)
	at com.cloudbees.groovy.cps.Next.step(Next.java:83)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:174)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:163)
	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:122)
	at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:261)
	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:163)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$101(SandboxContinuable.java:34)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.lambda$run0$0(SandboxContinuable.java:59)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.GroovySandbox.runInSandbox(GroovySandbox.java:108)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:58)
	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:174)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:332)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$200(CpsThreadGroup.java:83)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:244)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:232)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:131)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
Caused: java.util.concurrent.ExecutionException
	at org.jenkinsci.plugins.workflow.cps.CpsBodyExecution.get(CpsBodyExecution.java:299)
	at com.openshift.jenkins.plugins.pipeline.OcWatch$Execution$1.onReadLine(OcWatch.java:120)
Caused: java.io.IOException
	at com.openshift.jenkins.plugins.pipeline.OcWatch$Execution$1.onReadLine(OcWatch.java:133)
	at com.openshift.jenkins.plugins.util.ClientCommandRunner$OcOutputConsumer.call(ClientCommandRunner.java:75)
	at com.openshift.jenkins.plugins.util.ClientCommandRunner$OcOutputConsumer.call(ClientCommandRunner.java:60)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
Caused: java.util.concurrent.ExecutionException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.openshift.jenkins.plugins.util.ClientCommandRunner.run(ClientCommandRunner.java:172)
	at com.openshift.jenkins.plugins.pipeline.OcWatch$Execution.run(OcWatch.java:148)
	at com.openshift.jenkins.plugins.pipeline.OcWatch$Execution.run(OcWatch.java:75)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:47)
	at hudson.security.ACL.impersonate(ACL.java:290)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Finished: FAILURE
```
I believe this the code caused above exception: 

```
def scalePods (clusterName, tokenId, projectName, appName, replicaCount) {
    
    openshift.withCluster(clusterName, tokenId) {
        openshift.withProject(projectName) {
            if (openshift.selector('dc', appName).exists()) {
                def dcObj = openshift.selector('dc', appName).object()
                
                //scale pod
                openshift.apply(dcObj).scale("--replicas=${replicaCount}")
                
                def latestDeploymentVersion = dcObj.status.latestVersion
                echo "latestDeploymentVersion is ${latestDeploymentVersion}"
                
                def podSelector= openshift.selector('pod', [deployment: "${appName}-${latestDeploymentVersion}"])
                
                // do not watch if scale down
                if (podSelector.exists() && replicaCount != 0) {
                    podSelector.untilEach {
                        echo "pod: ${it.name()}"
                        return it.object().status.containerStatuses.every {
                            it.ready
                        }
                    }
                }
            }
        }
    }
}

```
My pod only has one container, but we scale up multiple pods. This exception only happened once after we ran this pipeline more than 10 times before, but it makes me worry, why it only happened intermittently? Why it.object() can throw exception? and how can I prevent it? Because we have not used it in production deployment yet. 

Thanks!

**Comment by waveywaves** [comment]
Hello @Joyce808 

wrt the pipeline, I am not sure of the containerStatuses syntax below. 

```
 // do not watch if scale down
                if (podSelector.exists() && replicaCount != 0) {
                    podSelector.untilEach {
                        echo "pod: ${it.name()}"
                        return it.object().status.containerStatuses.every { <<<<<<<<<<<<
                            it.ready
                        }
                    }
                }
```

Currently we are on 1.0.31 iteration of the pipeline and would suggest for you to use it.

Based on your scenario it would be better to check if the pod is up, as checking the contianer doesn't make sense as the pod state is dependent on the state of the containers inside of the pod. Like this >

```
openshift.withCluster( 'devcluster' ) {

    def maps = openshift.selector( 'dc', [ app: 'nodejs' ] )
    def objs = maps.objects()

    openshift.withCluster() {

        openshift.create( objs )
        maps.related( 'pods' ).untilEach {

            return it.object().status.phase == 'Running'

        }
    }
}
```

**Comment by Joyce808** [comment]
Hello @waveywaves,

Thanks very much for your help. 

Yes, it is a bit awkward to ask questions about a very old version. It is not very flexible for us to update the Jenkins plugins here, so we have to live with the old version for now. 

I agree it does not make sense to check the container's status inside a pod to see if the pod is running, it is better to check the pod status directly. I have tested your recommendation, and it works in my old client version, and I will use that in our next release. :-)

```
return it.object().status.phase == 'Running'
```
One more question, I'd like to checkout the 1.0.18 version of the jenkins-client-plugin to view the source code to know which method I can call, groovy does not automatically pops up those method like Java. How can I clone? 

Thanks!

**Comment by akram** [comment]
Hi @Joyce808 

to get the 1.0.18 code base, just use search for our "mvn release" commit with the proper version.
You can use the following command:
`
 git log --all --grep="1.0.18"
`

Then checkout this specific commit.
Please close this "issue" if you think that your questions are answered.

Greetings
Akram

/cc @waveywaves

**Comment by TomSchmitz** [comment]
Ich bin bis 05.08.2019 abwesend.
I am out of the office until 05.08.2019.

Ich werde Ihre Nachricht nach meiner Rückkehr beantworten.

In dringenden Fällen wenden Sie sich bitte an Frank Becker (AC-6606)


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re:
[openshift/jenkins-client-plugin] Unable to retrieve object markup with
get; action failed (#285)" gesendet am 01.08.2019 18:27:40.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während
diese Person abwesend ist.

**Comment by TomSchmitz** [comment]
Ich bin bis 05.08.2019 abwesend.
I am out of the office until 05.08.2019.

Ich werde Ihre Nachricht nach meiner Rückkehr beantworten.

In dringenden Fällen wenden Sie sich bitte an Frank Becker (AC-6606)


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re:
[openshift/jenkins-client-plugin] Unable to retrieve object markup with
get; action failed (#285)" gesendet am 04.08.2019 12:06:52.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während
diese Person abwesend ist.
