### ISSUE TITLE
java.nio.file.NoSuchFileException after upgrade to 1.0.37

### ISSUE THREAD

**Issue by rbaala1986** [openshift/jenkins-client-plugin#396]
We updated the jenkins-client-plugin to 1.0.37 and encountered the following error when executing openshift commands from Jenkins

java.nio.file.NoSuchFileException: /var/run/secrets/kubernetes.io/serviceaccount/namespace
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:371)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:422)
	at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420)
	at java.base/java.nio.file.Files.newInputStream(Files.java:156)
	at hudson.FilePath.newInputStreamDenyingSymlinkAsNeeded(FilePath.java:2209)
	at hudson.FilePath$Read.invoke(FilePath.java:2292)
	at hudson.FilePath$Read.invoke(FilePath.java:2278)
	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:3502)
	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:376)
	at hudson.remoting.InterceptingExecutorService.lambda$wrap$0(InterceptingExecutorService.java:78)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused: java.io.IOException
	at hudson.remoting.FastPipedInputStream.read(FastPipedInputStream.java:171)
	at java.base/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.base/java.io.InputStreamReader.read(InputStreamReader.java:181)
	at java.base/java.io.Reader.read(Reader.java:229)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1432)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1411)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:1208)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:1022)
	at org.apache.commons.io.IOUtils.toString(IOUtils.java:2839)
	at org.apache.commons.io.IOUtils.toString(IOUtils.java:2865)
	at org.jenkinsci.plugins.workflow.steps.ReadFileStep$Execution.run(ReadFileStep.java:110)
	at org.jenkinsci.plugins.workflow.steps.ReadFileStep$Execution.run(ReadFileStep.java:96)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Finished: FAILURE

**Comment by akram** [comment]
@rbaala1986 can you please describe how it is happening?
the provided stack trace does not have a line related to jenkins-client-plugin . But, instead, it seems to be: `at org.jenkinsci.plugins.workflow.steps.ReadFileStep`
